"""
POST /api/v1/query — Single public entry point for multi-agent execution.

Flow
----
1. Validate the incoming QueryRequest (Pydantic).
2. Reuse the X-Request-ID already generated by RequestLoggerMiddleware so the
   response body, response headers, and server logs all share one trace ID.
3. Invoke the compiled LangGraph pipeline:
       graph.invoke({"query": request.query, ...})
   LangGraph runs each agent node in order.
   Nodes broadcast WebSocket lifecycle events via execute_agent().
4. Extract planner_output from the returned state.
5. Return a structured QueryResponse.

Future agents (Research, Policy, Finance, etc.) are already wired into the
graph and their outputs will be surfaced here without changing the endpoint
contract.
"""

import uuid
from fastapi import APIRouter, Request

from app.orchestrator.graph import graph
from app.schemas.query import QueryRequest, QueryResponse
from app.core.logger import logger

router = APIRouter()


@router.post(
    "/query",
    response_model=QueryResponse,
    summary="Run the EarthMind AI multi-agent pipeline",
    description=(
        "Accepts a sustainability query, runs it through the LangGraph "
        "orchestration pipeline, and returns the structured Planner output."
    ),
)
async def run_query(fastapi_request: Request, request: QueryRequest) -> QueryResponse:
    """
    Entry point for all agent execution.

    This endpoint is intentionally thin — all business logic lives
    inside the LangGraph graph and individual agent nodes.
    """

    # Step 1: Reuse the request ID already set by RequestLoggerMiddleware.
    # This ensures the body's request_id == X-Request-ID response header,
    # giving end-to-end traceability across logs, headers, and response body.
    request_id_str = getattr(fastapi_request.state, "request_id", None)
    request_id = uuid.UUID(request_id_str) if request_id_str else uuid.uuid4()

    logger.info("[%s] Query received: %s", request_id, request.query)

    # Step 2: Invoke the LangGraph pipeline.
    # Run the synchronous graph.invoke in a worker thread to prevent blocking
    # the main event loop. This allows WebSocket events to be broadcast in
    # real-time and prevents deadlocks with synchronous LLM calls.
    import asyncio
    result = await asyncio.to_thread(
        graph.invoke,
        {
            "query": request.query,
            # Initialise optional state keys so BaseAgent.run() can safely
            # write agent_status and errors without raising KeyError.
            "agent_status": {},
            "errors": {},
            "retry_count": 0,
        },
    )

    logger.info("[%s] Pipeline completed successfully.", request_id)

    # Step 3: Build and return the typed response.
    return QueryResponse(
        request_id=request_id,
        status="completed",
        planner_output=result.get("planner_output", ""),
    )
