"""
POST /api/v1/query — Single public entry point for multi-agent execution.

Flow
----
1. Validate the incoming QueryRequest (Pydantic).
2. Reuse the X-Request-ID already generated by RequestLoggerMiddleware so the
   response body, response headers, and server logs all share one trace ID.
3. Build the complete initial GraphState — every key must be present so that
   nodes never encounter a KeyError when reading state.
4. Invoke the compiled LangGraph pipeline in a worker thread (non-blocking)
   so WebSocket events can be broadcast in real-time.
5. Extract every field from the returned state and return a QueryResponse.
6. Persist QueryHistory and ReportHistory via HistoryService (fire-and-forget
   semantics: persistence failures are logged but never surface to the caller).
"""

import time
import uuid
import asyncio
from fastapi import APIRouter, Depends, Request
from sqlalchemy.orm import Session

from app.orchestrator.graph import get_graph
from app.schemas.query import QueryRequest, QueryResponse
from app.core.logger import logger
from app.services.postgres import get_db
from app.services.history import history_service

router = APIRouter()


@router.post(
    "/query",
    response_model=QueryResponse,
    summary="Run the EarthMind AI multi-agent pipeline",
    description=(
        "Accepts a sustainability query, runs it through the LangGraph "
        "orchestration pipeline, and returns the full structured result."
    ),
)
async def run_query(
    fastapi_request: Request,
    request: QueryRequest,
    db: Session = Depends(get_db),
) -> QueryResponse:
    """
    Entry point for all agent execution.

    This route is intentionally thin — all business logic lives inside the
    LangGraph graph and individual agent nodes.
    """

    # ── Step 1: Reuse the request ID set by RequestLoggerMiddleware ───────────
    request_id_str = getattr(fastapi_request.state, "request_id", None)
    request_id = uuid.UUID(request_id_str) if request_id_str else uuid.uuid4()

    logger.info("[%s] Query received: %s", request_id, request.query)

    # ── Step 2: Build the complete initial state ──────────────────────────────
    # Every GraphState key MUST be initialized here.
    # Nodes read state keys directly; missing keys cause KeyError at runtime.
    initial_state = {
        "query":               request.query,
        "planner_output":      {},
        "required_agents":     [],
        "execution_order":     [],
        "outputs":             {},
        "agent_status":        {},
        "errors":              {},
        "missing_information": [],  # List of {type, description} objects
        "retrieved_context":   [],
        "tool_executions":     [],
    }

    # ── Step 3: Run the graph in a worker thread ──────────────────────────────
    # graph.invoke() is synchronous (LLM calls are blocking).
    # Running it in a thread pool prevents blocking the main event loop,
    # which allows WebSocket broadcasts to be delivered in real-time.
    start_time = time.perf_counter()
    result = await asyncio.to_thread(get_graph().invoke, initial_state)
    execution_time = time.perf_counter() - start_time

    logger.info(
        "[%s] Pipeline completed successfully in %.3fs.",
        request_id,
        execution_time,
    )

    # ── Step 4: Build and return the typed response ───────────────────────────
    outputs = result.get("outputs", {})

    # Report is stored as a raw Markdown string in outputs["report"]
    report = outputs.get("report", "")
    if not isinstance(report, str):
        # Safety: if report is somehow still a dict, try to extract text
        report = report.get("summary", "") if isinstance(report, dict) else str(report)

    # Extract lightweight RAG metadata from state (not raw chunks)
    retrieved_context = result.get("retrieved_context", [])
    retrieved_chunks = len(retrieved_context)
    retrieved_domains = sorted({
        chunk.get("domain") or "unknown"
        for chunk in retrieved_context
        if isinstance(chunk, dict)
    })

    # ── Step 5: Determine actual execution status (H-8) ──────────────────────
    # If any agent errors are present, the run is "partial" rather than
    # "completed", even if agents handled their own fallback gracefully.
    errors = result.get("errors", {})
    execution_status = "partial" if errors else "completed"

    # ── Step 6: Persist history (fire-and-forget) ─────────────────────────────
    # Persistence failures must never surface to the caller.
    planner_output = result.get("planner_output", {})
    confidence = planner_output.get("confidence") if isinstance(planner_output, dict) else None

    try:
        planner_output_for_db = dict(planner_output) if isinstance(planner_output, dict) else {}
        planner_output_for_db["tool_executions"] = result.get("tool_executions", [])

        query_record = history_service.save_query(
            db=db,
            query=request.query,
            planner_output=planner_output_for_db,
            execution_time=execution_time,
            status=execution_status,
            confidence=confidence,
        )
        history_service.save_report(
            db=db,
            query_id=query_record.id,
            report=report,
        )
    except Exception:
        logger.error(
            "[%s] History persistence failed — response unaffected.",
            request_id,
            exc_info=True,
        )

    return QueryResponse(
        request_id=request_id,
        status=execution_status,
        query=request.query,
        planner_output=planner_output,
        report=report,
        outputs={k: v for k, v in outputs.items() if k != "report"},
        agent_status=result.get("agent_status", {}),
        errors=errors,
        missing_information=result.get("missing_information", []),
        retrieved_chunks=retrieved_chunks,
        retrieved_domains=retrieved_domains,
        tool_executions=result.get("tool_executions", []),
    )
