"""
POST /api/v1/query — Single public entry point for multi-agent execution.

Flow
----
1. Validate the incoming QueryRequest (Pydantic).
2. Reuse the X-Request-ID already generated by RequestLoggerMiddleware so the
   response body, response headers, and server logs all share one trace ID.
3. Build the complete initial GraphState — every key must be present so that
   nodes never encounter a KeyError when reading state.
4. Invoke the compiled LangGraph pipeline in a worker thread (non-blocking)
   so WebSocket events can be broadcast in real-time.
5. Extract every field from the returned state and return a QueryResponse.
"""

import uuid
import asyncio
from fastapi import APIRouter, Request

from app.orchestrator.graph import get_graph
from app.schemas.query import QueryRequest, QueryResponse
from app.core.logger import logger

router = APIRouter()


@router.post(
    "/query",
    response_model=QueryResponse,
    summary="Run the EarthMind AI multi-agent pipeline",
    description=(
        "Accepts a sustainability query, runs it through the LangGraph "
        "orchestration pipeline, and returns the full structured result."
    ),
)
async def run_query(fastapi_request: Request, request: QueryRequest) -> QueryResponse:
    """
    Entry point for all agent execution.

    This route is intentionally thin — all business logic lives inside the
    LangGraph graph and individual agent nodes.
    """

    # ── Step 1: Reuse the request ID set by RequestLoggerMiddleware ───────────
    request_id_str = getattr(fastapi_request.state, "request_id", None)
    request_id = uuid.UUID(request_id_str) if request_id_str else uuid.uuid4()

    logger.info("[%s] Query received: %s", request_id, request.query)

    # ── Step 2: Build the complete initial state ──────────────────────────────
    # Every GraphState key MUST be initialized here.
    # Nodes read state keys directly; missing keys cause KeyError at runtime.
    initial_state = {
        "query":               request.query,
        "planner_output":      {},
        "required_agents":     [],
        "execution_order":     [],
        "outputs":             {},
        "agent_status":        {},
        "errors":              {},
        "missing_information": [],
        "retrieved_context":   [],
    }

    # ── Step 3: Run the graph in a worker thread ──────────────────────────────
    # graph.invoke() is synchronous (LLM calls are blocking).
    # Running it in a thread pool prevents blocking the main event loop,
    # which allows WebSocket broadcasts to be delivered in real-time.
    result = await asyncio.to_thread(get_graph().invoke, initial_state)

    logger.info("[%s] Pipeline completed successfully.", request_id)

    # ── Step 4: Build and return the typed response ───────────────────────────
    outputs = result.get("outputs", {})

    # Extract lightweight RAG metadata from state (not raw chunks)
    retrieved_context = result.get("retrieved_context", [])
    retrieved_chunks = len(retrieved_context)
    retrieved_domains = sorted({
        chunk.get("domain") or "unknown"
        for chunk in retrieved_context
        if isinstance(chunk, dict)
    })

    return QueryResponse(
        request_id=request_id,
        status="completed",
        query=request.query,
        planner_output=result.get("planner_output", {}),
        report=outputs.get("report", ""),
        outputs={k: v for k, v in outputs.items() if k != "report"},
        agent_status=result.get("agent_status", {}),
        errors=result.get("errors", {}),
        missing_information=result.get("missing_information", []),
        retrieved_chunks=retrieved_chunks,
        retrieved_domains=retrieved_domains,
    )
