/**
 * src/pdf/components/CoverPage.tsx
 */

import React from "react";
import { Page, View, Text } from "@react-pdf/renderer";
import { S, BRAND } from "../styles";
import type { ReportData } from "../types";

interface Props {
  data: Pick<
    ReportData,
    | "reportId"
    | "queryText"
    | "generatedDate"
    | "generatedTime"
    | "executionDuration"
    | "techInfo"
  >;
}

export function CoverPage({ data }: Props) {
  return (
    <Page size="A4" style={S.coverPage}>
      {/* ── Brand mark ── */}
      <View style={S.coverBadge}>
        <Text style={S.coverBadgeText}>EarthMind AI · Multi-Agent Platform</Text>
      </View>

      {/* ── Title block ── */}
      <Text style={S.h1}>Sustainability</Text>
      <Text style={S.h1}>Action Report</Text>

      <View style={S.coverDivider} />

      {/* ── Challenge ── */}
      <Text
        style={{
          fontSize: 11,
          color: "#94a3b8",
          marginBottom: 6,
          fontFamily: "Helvetica-Bold",
          textTransform: "uppercase",
          letterSpacing: 0.7,
        }}
      >
        Challenge
      </Text>
      <Text
        style={{
          fontSize: 13,
          color: BRAND.white,
          fontFamily: "Helvetica-Bold",
          lineHeight: 1.4,
          maxWidth: 400,
        }}
      >
        {data.queryText}
      </Text>

      {/* ── Meta grid ── */}
      <View style={S.coverMetaGrid}>
        {[
          { label: "Generated",        value: data.generatedDate },
          { label: "Time",             value: data.generatedTime },
          { label: "Duration",         value: data.executionDuration },
          { label: "Standard",         value: "CSRD · ESRS · SDG" },
          { label: "Report ID",        value: data.reportId },
          { label: "Report Version",   value: "v1.8.4" },
          { label: "Generated By",     value: "EarthMind AI Multi-Agent Runtime" },
          { label: "Platform Version", value: "EMAI-Runtime v1.7.8" },
        ].map((item) => (
          <View key={item.label} style={S.coverMetaCell}>
            <Text style={S.coverMetaLabel}>{item.label}</Text>
            <Text style={S.coverMetaValue}>{item.value}</Text>
          </View>
        ))}
      </View>

      {/* ── Footer tagline ── */}
      <View
        style={{
          position: "absolute",
          bottom: 40,
          left: 40,
          right: 40,
        }}
      >
        <View
          style={{
            borderTopWidth: 1,
            borderTopColor: "#334155",
            borderStyle: "solid",
            paddingTop: 12,
          }}
        >
          <Text
            style={{
              fontSize: 7,
              color: "#475569",
              textAlign: "center",
              textTransform: "uppercase",
              letterSpacing: 1,
            }}
          >
            Generated using EarthMind AI · IBM watsonx.ai · LangGraph · ChromaDB
          </Text>
        </View>
      </View>
    </Page>
  );
}
