from abc import ABC, abstractmethod
import logging
import time

from app.services.llm import get_llm

logger = logging.getLogger(__name__)


class BaseAgent(ABC):
    """
    Base class for all AI agents.
    Every agent must implement build_prompt().
    """

    def __init__(self):
        self.llm = get_llm()

    @abstractmethod
    def build_prompt(self, state):
        """
        Build the prompt for the agent.
        Must return a string.
        """
        pass

    def run(self, state):
        """
        Executes the LLM using the prompt generated by build_prompt().
        Returns ONLY the generated text.
        """

        agent_name = self.__class__.__name__
        start = time.time()

        try:

            prompt = self.build_prompt(state)

            MAX_RETRIES = 3

            for attempt in range(MAX_RETRIES):

                try:
                    response = self.llm.invoke(prompt)

                    logger.info("%s completed", agent_name)

                    return response.content

                except Exception as e:

                    if attempt == MAX_RETRIES - 1:
                        raise e

            return ""

        except Exception as e:

            logger.exception("%s failed: %s", agent_name, str(e))
            raise

        finally:

            logger.info(
                "%s finished in %.2fs",
                agent_name,
                time.time() - start,
            )